apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: gcr.io/montycarter-gke-dev/hello_world:latest
          env:
            - name: TARGET
              value: "Go Sample v1"
