steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull gcr.io/montycarter-gke-dev/http_server:latest || exit 0
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/montycarter-gke-dev/http_server:latest', '--cache-from', 'gcr.io/montycarter-gke-dev/http_server:latest', '.' ]
images: ['gcr.io/montycarter-gke-dev/http_server:latest']
